@localhostV1 = http://localhost:3000/api/v1
# @username = gofiber
# @password = 21022566
# Basic {{base64Encode username + ":" + password}}
@authorizationHeader = Basic Z29maWJlcjoyMTAyMjU2Ng==



### GET | GetDogsSum
GET {{localhostV1}}/dog/sum
Authorization: {{authorizationHeader}}

### GET | GetDogsGreaterThan50LessThan100
GET {{localhostV1}}/dog/gt50lt100
Authorization: {{authorizationHeader}}



### DELETE | SoftRemoveDog
DELETE http://localhost:3000/api/v1/dog/soft/1
Authorization: {{authorizationHeader}}

### GET | GetSoftRemovedDogs
GET http://localhost:3000/api/v1/dog/soft
Authorization: {{authorizationHeader}}



### GET /api/dog
GET {{localhostV1}}/dog
Authorization: {{authorizationHeader}}

### GET /api/dog/filter?search=<your_search_value>
GET {{localhostV1}}/dog/filter?search=0
Authorization: {{authorizationHeader}}

### GET /api/dog/json
GET {{localhostV1}}/dog/json
Authorization: {{authorizationHeader}}

### POST /api/dog
POST {{localhostV1}}/dog
Content-Type: application/json
Authorization: {{authorizationHeader}}

{
  "name": "DogName",
  "dog_id": 51,
  "type": "Red"
}

### PUT /api/dog/:id
PUT {{localhostV1}}/dog/9
Content-Type: application/json
Authorization: {{authorizationHeader}}

{
  "name": "UpdatedDogName",
  "dog_id": 101,
  "type": "Blue"
}

### DELETE /api/dog/:id
DELETE {{localhostV1}}/dog/13
Authorization: {{authorizationHeader}}
